# Generated by Django 5.2.4 on 2025-07-18 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='description',
        ),
        migrations.AddField(
            model_name='objective',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objective',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='objective',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
