# Generated by Django 5.2.4 on 2025-07-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_remove_objective_description_objective_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
